### ISSUE TITLE
[feat] Introduce the date display?

### ISSUE THREAD

**Issue by li0817** [udus122/checkbox-time-tracker#62]
Just like this.
![image](https://github.com/udus122/checkbox-time-tracker/assets/27659768/07332237-2031-4622-9514-9b40d75ac0d6)

**Comment by udus122** [comment]
@li0817 Thank you for your request.
It seems possible.

I'll try it and comment when I've done it.

**Comment by udus122** [comment]
@li0817 I've made some changes that allow you to customise the date, time, and delimiters to be inserted.

Therefore, after updating to the latest version (0.8.1), if you set it up as follows, you should be able to display it as shown in the example.

Please give it a try.

![screenshot_20240615170717](https://github.com/udus122/checkbox-time-tracker/assets/22557372/ae0c663b-b5c8-4972-8f06-cf06813d7ece)

**Comment by li0817** [comment]
> @li0817 I've made some changes that allow you to customise the date, time, and delimiters to be inserted.
> 
> Therefore, after updating to the latest version (0.8.1), if you set it up as follows, you should be able to display it as shown in the example.
> 
> Please give it a try.
> 
> ![screenshot_20240615170717](https://private-user-images.githubusercontent.com/22557372/339966360-ae0c663b-b5c8-4972-8f06-cf06813d7ece.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTUzMDksIm5iZiI6MTcxODc5NTAwOSwicGF0aCI6Ii8yMjU1NzM3Mi8zMzk5NjYzNjAtYWUwYzY2M2ItYjVjOC00OTcyLThmMDYtY2YwNjgxM2Q3ZWNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMmYyZjg3MjYxNjI1MmFmYzgyMzk5Y2M0NTJlYjYzOTc1NDU5YTE1ZGZkMDEzNDZmY2VmY2VjM2Y3ZjU3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bWqhbdbqN5AP0cuwOMfYZp1SOeVEGwaTBIqQQQR-1sw)

Thanks! That's very helpful.
